In [2]:
class demo:
    def test(self):
        print("test()for the class and method")
        return
obj=demo()
obj.test()

test()for the class and method


In [4]:
 def test():
    print("test()for fuction")
    return
test()
 

test()for fuction


In [12]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact* n
            n=n-1
            
        return fact
    
p1=demo1()
print(p1.fact(5))#120

120


In [24]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
            return p1+p2
        
c1=demo2(10,20)
print(c1.add(100,200))
        

300


In [34]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
    
class employee(person):
        def isemployee(self):
            return True
        
emp=person("Anil")
print(emp.getname(),emp.isemployee())
    
emp1=employee("Akhil")
print(emp1.getname(),emp1.isemployee())

Anil False
Akhil True


In [37]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [39]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [40]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [45]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [47]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [49]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [52]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [53]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)


[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [57]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [59]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [60]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,1])

slicing column : [2 5]


In [61]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last column :",a1[:,2])

slicing last column : [3 6]


In [62]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [63]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[5.29745358 3.98503971 4.70425719 4.92560753 5.42558518 5.25075663
 4.76045248 4.77277335 3.89519081 4.76448718]
min value= 3.8951908058327946
max value= 5.425585177162369
mean value= 4.778160363375699
median value= 4.7686302647906516


In [64]:
c1=np.array([1,2])
c2=np.array([4,3])
np.dot(c1,c2)

10

In [65]:
c1=np.array([(1,2),(1,4)])
c2=np.array([(1,4),(1,2)])
np.dot(c1,c2)

array([[ 3,  8],
       [ 5, 12]])

In [83]:
import pandas as pd
dict = {"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
       "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kran@gmail.com"],
        "MobileNumber":[999,888,777,888,777,999],
        "Address":["Vmd","Vmd","Vmd","Vmd","Vmd","Vmd"]}
b=pd.DataFrame(dict)
print(b)
        

AttributeError: module 'pandas' has no attribute '_libs'